const charList = [
    //character, searches, picture
    ["Albedo <br> Banner", 11816107, "images/characters/albedo.webp"],
    ["Arataki Itto <br> Banner", 13404072, "images/characters/itto.webp"],
    ["Eula <br> Banner", 12619390, "images/characters/eula.webp"],
    ["Ganyu <br> Banner", 15669918, "images/characters/ganyu.webp"],
    ["Hu Tao <br> Banner", 12481634, "images/characters/hutao.webp"],
    ["Hu Tao <br> Rerun", 25226952, "images/characters/hutao.webp"],
    ["Ayaka <br> Banner", 16451006, "images/characters/ayaka.webp"],
    ["Kazuha <br> Banner", 9807112, "images/characters/kazuha.webp"],
    ["Keqing <br> Banner", 9505798, "images/characters/keqing.webp"],
    ["Klee <br> Banner", 22750080, "images/characters/klee.webp"],
    ["Klee <br> Rerun", 7006180, "images/characters/klee.webp"],
    ["Raiden Shogun <br> Banner", 33020905, "images/characters/raiden.webp"],
    ["Kokomi <br> Banner", 7020975, "images/characters/kokomi.webp"],
    ["Tartaglia <br> Banner", 13443619, "images/characters/tartaglia.webp"],
    ["Tartaglia <br> Rerun", 6965445, "images/characters/tartaglia.webp"],
    ["Tartaglia <br> Rerun 2", 7785438, "images/characters/tartaglia.webp"],
    ["Venti <br> Banner", 30632752, "images/characters/venti.webp"],
    ["Venti <br> Rerun", 16614209, "images/characters/venti.webp"],
    ["Xiao <br> Banner", 13145115, "images/characters/xiao.webp"],
    ["Yae Miko <br> Banner", 15110264, "images/characters/yae.webp"],
    ["Yoimiya <br> Banner", 8615144, "images/characters/yoimiya.webp"],
    ["Zhongli <br> Banner", 16264892, "images/characters/zhongli.webp"],
    ["Zhongli <br> Rerun", 10215165, "images/characters/zhongli.webp"],

//double <br> Banner rerun
    ["Albedo/Eula <br> Double Banner", 17026066, "images/characters/albedo-eula.webp"],
    ["Ayato/Venti <br> Double Banner", 22767455, "images/characters/ayato-venti.webp"],
    ["Zhongli/Ganyu <br> Double Banner", 26780298, "images/characters/zhongli-ganyu.webp"],
    ["Raiden/Kokomi <br> Double Banner", 33560259, "images/characters/raiden-kokomi.webp"],
    ["Shenhe/Xiao <br> Double Banner", 16994406, "images/characters/shenhe-xiao.webp"],
]